### ISSUE TITLE
UTF-8 Column Names Throw Error

### ISSUE THREAD

**Issue by mattwilliamson** [driftx/Telephus#12]
Try using **Иона** as the column name in the tests and you'll see the following exception:

```
Traceback (most recent call last):
  File "/Users/mwilliamson/Projects/Telephus/telephus/protocol.py", line 200, in reqError
    raise err.value
exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```

don't forget to add the encoding declaration in the test file:

```
# -*- coding: utf-8 -*-
```

**Comment by mattwilliamson** [comment]
This was on the 0.7 branch

**Comment by thepaul** [comment]
Cassandra column names are sequences of bytes, not Unicode strings. If you want to represent Unicode strings in column names, you'll need to choose some encoding to get from code points to bytes. UTF-8 is often a good choice.

Try encoding your Unicode strings in utf-8 before using them as column names:

```
columnname = u'Иона'
columnbytes = columnname.encode('utf-8')
d = client.insert('key', 'columnfamily', 'myvalue', column=columnbytes)
```

**Comment by mattwilliamson** [comment]
I'll do that. Is that what's done for column values? I don't get the error on values.

**Comment by thepaul** [comment]
Yes, the situation is the same for column values.
