### ISSUE TITLE
Use rpc_address for connection pooling auto discovery

### ISSUE THREAD

**Issue by nickmbailey** [driftx/Telephus#18]
With https://issues.apache.org/jira/browse/CASSANDRA-1777 and https://issues.apache.org/jira/browse/CASSANDRA-3187 the call to describe_ring will return both the listen_address and the rpc_address of nodes. The connection pooling code should prefer the rpc_address when auto-discovering nodes. It will also need some additional logic to revert back to the listen_address if the rpc_address is something like '0.0.0.0'.

**Comment by thepaul** [comment]
This was fixed in #33.
