### ISSUE TITLE
Test Script Ambiguous

### ISSUE THREAD

**Issue by mattwilliamson** [driftx/Telephus#2]
Hello, I am using your test/test_cassandraclient.py as a reference, but all the values are like "test" and "test2". Could you please update these to something that describes what they are, e.g. "value test" or something so we can tell what the arguments are and that we aren't retrieving a wrong column with the same value.

**Comment by mattwilliamson** [comment]
Also to tell the difference between keys and values.

**Comment by driftx** [comment]
Args are now kwargified for clarity.

**Comment by mattwilliamson** [comment]
thanks!
