### ISSUE TITLE
cannot set consistency of cassandraClusterPool object

### ISSUE THREAD

**Issue by praveen-p** [driftx/Telephus#21]
consistency of a CassandraClusterPool object cannot be set by assigning a value to it.  CassandraClusterPool uses property() method to set consistency, but  CassandraClusterPool is not a new-style-class.  (base class service.Service is not new-style-class) and property() only works for new-style-classes.  making CassandraClusterPool new-style-class will fix the issue.

**Comment by praveen-p** [comment]
im using Twisted-11.0.0

**Comment by thepaul** [comment]
You're quite right. It looks like it will be sufficient to add object to the bases for CassandraClusterPool, but I'll run some tests just to make sure nothing there relies on MRO or other old-style behavior.
