### ISSUE TITLE
Error in Telephus / telephus / pool.py

### ISSUE THREAD

**Issue by koblas** [driftx/Telephus#42]
Was reading the code for another reason, but noticed a missing `self.` on the protocol.ClientFactory.stopFactory(....)

```
def stopFactory(self):
    # idempotent
    self.logstate('stopFactory')
    protocol.ClientFactory.stopFactory(self)
    if self.connector:
        try:
```

**Comment by thobbs** [comment]
In this case, it's just calling the superclass (`twisted.internet.protocol.ClientFactory`) method, not anything on the class attribute `protocol`.

Thanks for taking the time to report this, though.
