### ISSUE TITLE
Update the definition of a column family

### ISSUE THREAD

**Issue by mateo41** [driftx/Telephus#7]
Hi folks,

I've been using the secondary index capabilities in Cassandra 0.7-rc2 and in Telephus. I've been able to create and query the indexes using Telephus. I got a lot of mileage out of the test_cassandraclient.py script.

However I'm trying to see if it is possible to update a column family's definition. I want to use system_update_column_family, but I get an error

Failure: telephus.cassandra.ttypes.InvalidRequestException: InvalidRequestException(why='ids do not match.')

I've put the script in a repository on github, that demonstrates this behavior. 
https://github.com/mateo41/TelephusExamples/blob/master/test_update_column_family.py

Could you let me know if I'm using the Telephus library incorrectly?

Thanks,
Matt

**Comment by driftx** [comment]
You need to get the CF id from describe_keyspace first, then pass it to system_update_column_family.

**Comment by thepaul** [comment]
Closing this issue. Let us know if you need something else.
